function options = gen_project_options_subtask(projectpath, projectname, filename, sim_time, savefig)
    check_path_exist(projectpath);
    outputpath = strcat(projectpath, "\\", projectname, "\\");
    check_path_exist(outputpath);
    key = {'projectpath', 'foldername', 'filename', 'lineStyle', 'markerStyle', 'savefig', ...
        'title_font_size', 'sgtitle_font_size', 'label_font_size', 'legend_font_size', ...
        'labely_pos', 'savepdf'};
    value = {projectpath, outputpath, filename, '--', 'none', savefig, ...
        12, 14, 12, 10, ...
        -sim_time/15, false};
    options = containers.Map(key, value);
end
